### ISSUE TITLE
训练时间和内存

### ISSUE THREAD

**Issue by catherinezll95** [yfsong0709/RA-GCNv1#1]
您好，感谢您提供的开源代码。请问在NTU RGB+D上训练需要多长时间，大概需要的内存是多少呢？

**Comment by yfsong0709** [comment]
这个训练时间是个大问题。想要寻找更多的信息，肯定会导致模型参数量变大的。目前来看2 streams的效果已经挺好了，时间的话4个TITAN X需要一天左右。GPU占用的话自己设定batch size调整就行。以后的研究可以从缩减每条stream的参数量入手，降低训练时间。

**Comment by catherinezll95** [comment]
感谢您的回答。我想请问，我阅读您论文的时候，发现您的baseline是准确率远高于ST-GCN，主要原因是因为您的数据增强策略吗？如果可以的话，希望能够与您通过微信，多进行学习交流。我目前是搞骨架行为识别研究生。

2019-05-27 09:29:37YFSong <notifications@github.com>写道：

这个训练时间是个大问题。想要寻找更多的信息，肯定会导致模型参数量变大的。目前来看2 streams的效果已经挺好了，时间的话4个TITAN X需要一天左右。GPU占用的话自己设定batch size调整就行。以后的研究可以从缩减每条stream的参数量入手，降低训练时间。

**Comment by yfsong0709** [comment]
对，这个数据增强挺重要的，特别是帧间差，对正确率影响很多。关于这个你可以关注一下PB-GCN和SR-TSL。
