### ISSUE TITLE
Error when trying to run on a single GPU

### ISSUE THREAD

**Issue by carterpaul** [yfsong0709/RA-GCNv1#4]
Hi, thank you for providing your source code. I understand that you ran it on two GPUs. I am trying to run it on a single GPU and am running into problems. I am just trying to run the pre-trained models for now before training my own.

Using CUDA version 9.0, Python 3.7.3, Pytorch 0.4.1

I changed gpus: [0,1] to gpus: [0] in the config file, but now I get another error:

> python main.py -c 3302 -p ~/DARAS/Public_Data/nturgb+d_skeletons -e
> 
> ************************************************
> The running config is presented as follows:
> path: /home/mmrnc/DARAS/Public_Data/nturgb+d_skeletons
> config_id: 3302
> resume: False
> evaluate: True
> extract: False
> visualization: False
> gpus: [0]
> seed: 1
> visualize_sample: 0
> visualize_class: 0
> visualize_stream: 0
> visualize_frames: []
> subset: cs
> max_frame: 300
> batch_size: 16
> data_transform: True
> occlusion_part: []
> occlusion_time: 0
> pretrained: True
> model_stream: 2
> gcn_kernel_size: [5, 2]
> drop_prob: 0.5
> max_epoch: 50
> learning_rate: 0.1
> adjust_lr: [10, 30]
> ************************************************
> 
> Starting preparing ...
> GPU0 used: 492.25M
> Traceback (most recent call last):
>   File "main.py", line 110, in <module>
>     main()
>   File "main.py", line 54, in main
>     p = Processor(args)
>   File "/home/mmrnc/DARAS/RA-GCN/RA-GCNv1/src/processor.py", line 59, in __init__
>     self.optimizer = nn.DataParallel(self.optimizer)
>   File "/home/mmrnc/anaconda3/envs/Py373Torch041Cuda9/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 114, in __init__
>     self.module.cuda(device_ids[0])
> AttributeError: 'SGD' object has no attribute 'cuda'

The error does not happen when I run on only the CPU with CUDA_VISIBLE_DEVICES = "". It seems to run the model fine, but very slow of course.

**Comment by yfsong0709** [comment]
I see. There is an error while using nn.DataParallel with CPU. I will fix it soon.

**Comment by yfsong0709** [comment]
Fixed. Optimizer should not use nn.DataParallel. You can try it again. Thanks for your feedback.
