### ISSUE TITLE
ColorX, ColorY in skeleton data

### ISSUE THREAD

**Issue by thancaocuong** [yfsong0709/RA-GCNv1#6]
Hi, I dont know why the ColorX and ColorY of Kinnect v2 was taken from 1920x1080 camera. But I get in dataset colorX exceeds 1920 and colorY was a negative value. please explain to me. thank you so much.

**Comment by yfsong0709** [comment]
Maybe you are confused by the starting number of matlab and python. In python, the number starts from 0, while in matlab it starts from 0. So, in python, you need to read jointinfo(5) and (6) for getting colorX and colorY.

**Comment by yfsong0709** [comment]
Maybe you are confused by the starting number of matlab and python. In python, the number starts from 0, while in matlab it starts from 1. So, in python, you need to read jointinfo(5) and (6) for getting colorX and colorY.

**Comment by thancaocuong** [comment]
yes, I did read jointinfo(5) and (6) followed your code 
```
location[0,frame,joint,person] = float(v[5])
location[1,frame,joint,person] = float(v[6])
```
that is the location that you get to visualize the skeleton.
But  when I check it, some locations are abnormal with x > 1920 or y > 1080.
Could you explain to me?

**Comment by yfsong0709** [comment]
Sorry, I dont know the reason. This reading code is based on the code released by the NTU authors. Maybe some of the original data are wrong, you can ask the NTU authors for more help.

**Comment by thancaocuong** [comment]
thank you. I will ask the NTU author and close this issue.
