### ISSUE TITLE
code about SR-TSL

### ISSUE THREAD

**Issue by jinchensuyun** [yfsong0709/RA-GCNv1#7]
@yfsong0709  hi,thank for your contribution.
i want to konw if  you have the code of ST-TSL? could you share the code with me?
Thank you very much!!!!

**Comment by yfsong0709** [comment]
SR-TSL is owned by its authors, and you need to ask them for help. Maybe you can search 2s-AGCN in github. It is a more accurate model for skeleton-based action recognition.

**Comment by jinchensuyun** [comment]
thank you for your help! XD
